language: python
python:
- '2.7'
sudo: false
addons:
  apt:
    update: true
env:
  matrix:
  - |-
    TOOLCHAIN_DIR="${HOME}/toolchain"
    ARM_TOOLCHAIN_URL="https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q3-update/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2"
    ARM_BINDIR="${TOOLCHAIN_DIR}/gcc-arm-none-eabi/bin"
    ESP8266_TOOLCHAIN_URL="http://arduino.esp8266.com/linux64-xtensa-lx106-elf.tar.gz"
    ESP8266_BINDIR="${TOOLCHAIN_DIR}/xtensa-lx106-elf/bin"
    ESP32_TOOLCHAIN_URL="https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-61-gab8375a-5.2.0.tar.gz"
    ESP32_BINDIR="${TOOLCHAIN_DIR}/xtensa-esp32-elf/bin"
    PATH="${PATH}:${ARM_BINDIR}:${ESP8266_BINDIR}:${ESP32_BINDIR}"
  global:
  - secure: h4xzPrWIwRbdOTxq1jTzAd8aFM7LLrmCvGyDcQqbccBbGkVOvTJ7+CC936G4OkkouO/m6bPKrTlK8DVBQI/b1mvKHFQYAnjyZeo9dl6ofNgHYMfYxnuhBSjQHzDYnsuS+Qa2xVIwOXgeyxZJh68YLRRvDWbtQ/3seWacSDNEVY6ZN+KmPn3CFIFozDdj5x+lN1mOBbvdQ1rtgSSak2ykiCCj9fqquGEJjo0a3C5C389B+dYW+AQergci8/NM505ggNi/tkFolriFo+swP9jDv+yGFiNB8icXvwJjI6KIKaVn6D/9Ueapg5JOrRfHslILQjNd6pHIcPFxAf9MEL10xlfkqC8PQu8AlrKH/Px2JQxEHQX6sygS2n2HdDyA9aXudBDbtBi4ldC17BV3hFKEuZuOyBauqWRJ5WhMXfu3iWUj1Hs5YjUDQL3k41m7QeKOFDJIzZ3UuMKXxA92PfdRY1T5YHutgQM/t5+QWUzJ8X3YffMSFHurgwGEJiW+WimneAn0BMtzSQwitzSwPQe8H+IQhkETelvbVx1c9kzncccE5JdDqwJSqHqFPJ289McO+IKLn0EXcOpRJFeD2I6+s3h573OK8RSGPiP+WJVph5Mccq4ZBtTt+4py969hnQsakMLbmVxR/rsVwjvJ6eRmeuyxK44qP9utLgPYZBLX4Vk=
  - secure: RF26URENpnNmbf1yK7/wzoeiROtFUIQSHILPtiWmPRk21nRah05bPGsWt00ayL4kn2rh+QAd4yKj+nfMl3JgKKxVCoLV4DNYBQ4m8RJYBVysVT7DGpQc6Kb9womoMovDlFSG2/vPf/INz/xaPIymGDW37JigJqtA/nwRMrX7cnxJVsaSLGAf9l+EW31d+VMR4nKAf9JVDfScWPej27mpQFzFSaIGr/8xGNWatknaaMD+4x0gJHdlZ6mLraY1qW8fiGPtyTrK3v4WCykLzRySzUsezBKd+fHuAado8TcKvY8xRXYor8xDKFd0tEPnF6aHgx5ZHzohrHpsq1xGhm2RVDz/ROC8OWTE962IVu3k07rBT85vd6wdWfudnR5pwgP7iLt8jSYSBV6nOpKJhJ9iFbZ+SYTn0sEOyfKuCithgmrVTHsQObtl2tPE96eM6WOCc3iLxm85cVXNdzZnBH4MOEGHkCZuUgsuFmUdsGiTXdb3ROtB0zGkrD+Enj9/BB08v7bZNCX/kKoqE2frB/wXHu6K2O3GAYgcztIh+ueU3yu/LflPuKB8e6HkoG0K9Jggs1M7NFJGBI9lYTuVmGGLPhCpf2cG6GKEOTOa3KHknV2UvGTDPRO5TlnD2KQ6n9Bm/0BN2O8qgFIYLboRVTePz4MZQIzCu9uBuPm437IzNAc=
before_install:
- sudo apt purge oracle-java8-installer oracle-java9-installer
- sudo apt autoremove
- sudo apt install -qq scons
- sudo apt install -qq gcc-multilib
- sudo apt install -qq libssl-dev libssl-dev:i386
- sudo apt install -qq libncurses5-dev libncurses5-dev:i386
- sudo apt install -qq libreadline-dev libreadline-dev:i386
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60
install:
- pwd
- cd ${HOME}
- mkdir -p ${TOOLCHAIN_DIR}
- wget ${ARM_TOOLCHAIN_URL} -O gcc-arm-none-eabi.tar.bz2
- tar xaf gcc-arm-none-eabi.tar.bz2 && mv gcc-arm-none-eabi-5_4-2016q3 ${TOOLCHAIN_DIR}/gcc-arm-none-eabi
- wget ${ESP8266_TOOLCHAIN_URL} -O linux64-xtensa-lx106-elf.tar.gz
- tar xaf linux64-xtensa-lx106-elf.tar.gz -C ${TOOLCHAIN_DIR}
- wget ${ESP32_TOOLCHAIN_URL} -O xtensa-esp32-elf-linux64.tar.gz
- tar xaf xtensa-esp32-elf-linux64.tar.gz -C ${TOOLCHAIN_DIR}
- pip install aos-cube
- cd ${TRAVIS_BUILD_DIR}
- git clone https://github.com/Cheng-SG/kconfig-frontends-linux.git build/kconfig
before_script:
- cd ${TRAVIS_BUILD_DIR}
- echo "export PATH=""${PATH}" >> ~/.bashrc
- echo ${TRAVIS_COMMIT}
- echo ${TRAVIS_PULL_REQUEST}
- echo ${TRAVIS_JOB_NUMBER}
script:
- echo -e "stm32f103rb-nucleo\nstm32f429zi-nucleo\nmk3080\nesp32devkitc\nesp8266\npca10040" > boards.txt
- bash ./build/scripts/autobuild.sh boards.txt
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then DIRNAME=push MARK=push; else DIRNAME=pr
  MARK=${TRAVIS_PULL_REQUEST}; fi
